"""added association

Revision ID: 68270b63e257
Revises: b02dfabcebda
Create Date: 2024-03-25 16:32:37.795358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68270b63e257'
down_revision = 'b02dfabcebda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
