"""added dict

Revision ID: 89c22595b295
Revises: 68270b63e257
Create Date: 2024-03-25 16:41:03.003931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c22595b295'
down_revision = '68270b63e257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
