"""restructured models

Revision ID: f47318bfa7b8
Revises: 89c22595b295
Create Date: 2024-03-25 16:47:27.978226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47318bfa7b8'
down_revision = '89c22595b295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
